name: Terraform CI

on:
  pull_request:
    branches:
      - main  

jobs:
  terraform_ci:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Enforce Formatting Rules
        if: steps.fmt.outcome == 'failure'
        run: |
          echo "::error title=Terraform Format Check Failed::Please run 'terraform fmt -recursive' to fix formatting issues."
          exit 1

      - name: Upload Terraform Debug Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-debug-logs
          path: .terraform*
